name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or SHA) to build'
        required: false
        type: string
        default: ''
      target_preset:
        description: 'Target preset to build'
        required: false
        type: choice
        options:
          - all
          - windows
          - linux
          - macos
          - mobile
          - musl
        default: 'all'
      skip_tests:
        description: 'Skip tests'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  test:
    if: ${{ !inputs.skip_tests && github.event_name != 'push' || github.ref_type != 'tag' }}
    uses: CaddyGlow/homebrew-packages/.github/workflows/rust-test.yml@main
    with:
      ref: ${{ inputs.ref || '' }}

  build:
    needs: [test]
    if: |
      always() &&
      !cancelled() &&
      (needs.test.result == 'success' || needs.test.result == 'skipped') &&
      (startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch')
    uses: CaddyGlow/homebrew-packages/.github/workflows/rust-build.yml@main
    with:
      ref: ${{ inputs.ref || '' }}
      binaries: '["shelltape"]'
      assets: '["README.md"]'
      target_preset: ${{ inputs.target_preset || 'all' }}

  release:
    needs: [build]
    if: |
      always() &&
      !cancelled() &&
      needs.build.result == 'success' &&
      startsWith(github.ref, 'refs/tags/')
    uses: CaddyGlow/homebrew-packages/.github/workflows/rust-release.yml@main
    with:
      ref: ${{ inputs.ref || '' }}
