name: CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: CaddyGlow/homebrew-packages/.github/workflows/rust-ci.yml@main
    with:
      binaries: '["shelltape"]'
      assets: '["README.md"]'
